"use client"

import { useRouter } from "next/navigation"

export default function TermsPage() {
  const router = useRouter()

  return (
    <div className="relative flex min-h-screen w-full flex-col max-w-md mx-auto bg-background shadow-2xl">
      {/* Header */}
      <div className="sticky top-0 z-50 flex items-center bg-background/95 backdrop-blur-md p-4 justify-between border-b border-border">
        <button
          onClick={() => router.back()}
          className="flex size-10 shrink-0 items-center justify-center rounded-full hover:bg-muted transition-colors"
        >
          <span className="material-symbols-outlined">arrow_back_ios_new</span>
        </button>
        <h2 className="text-base font-bold">Terms of Service</h2>
        <div className="w-10"></div>
      </div>

      <main className="flex-1 px-6 py-8 prose prose-sm max-w-none">
        <p className="text-muted-foreground text-sm mb-6">Last updated: January 2025</p>

        <h2 className="text-lg font-bold mt-6 mb-3">Agreement to Terms</h2>
        <p>
          By using Bible for Life Stages ("the app"), you agree to these Terms of Service. 
          If you disagree with any part, please do not use the app.
        </p>

        <h2 className="text-lg font-bold mt-6 mb-3">Description of Service</h2>
        <p>
          Bible for Life Stages provides personalized devotional content using artificial intelligence. 
          The app generates interpretations, stories, poetry, and reflections based on Bible verses 
          tailored to your life stage and circumstances.
        </p>

        <h2 className="text-lg font-bold mt-6 mb-3">AI-Generated Content Disclaimer</h2>
        <p>
          <strong>Important:</strong> Content in this app is generated by artificial intelligence and 
          is intended for devotional and inspirational purposes only. AI-generated content:
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Should not replace guidance from pastors, counselors, or qualified professionals</li>
          <li>May occasionally contain inaccuracies or misinterpretations</li>
          <li>Is not a substitute for professional mental health support</li>
          <li>Should be considered alongside traditional Bible study and community</li>
        </ul>

        <h2 className="text-lg font-bold mt-6 mb-3">Subscriptions & Payments</h2>
        <h3 className="text-base font-semibold mt-4 mb-2">Free Tier</h3>
        <p>Basic features are available free of charge with limited functionality.</p>
        
        <h3 className="text-base font-semibold mt-4 mb-2">Premium Subscription</h3>
        <ul className="list-disc pl-5 space-y-1">
          <li>Monthly: $5/month</li>
          <li>Yearly: $45/year (25% savings)</li>
        </ul>
        
        <h3 className="text-base font-semibold mt-4 mb-2">Free Trial</h3>
        <p>
          New users may receive a 7-day free trial of Premium features. After the trial, 
          you will need to subscribe to continue accessing Premium features.
        </p>

        <h3 className="text-base font-semibold mt-4 mb-2">Billing</h3>
        <p>
          Subscriptions are processed through Apple App Store or Google Play Store. 
          Billing terms, cancellation, and refunds are governed by the respective store's policies.
        </p>

        <h2 className="text-lg font-bold mt-6 mb-3">Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Use the app for any unlawful purpose</li>
          <li>Attempt to reverse engineer or extract the AI models</li>
          <li>Share your subscription access with others</li>
          <li>Use automated systems to access the app excessively</li>
          <li>Misrepresent AI-generated content as official religious doctrine</li>
        </ul>

        <h2 className="text-lg font-bold mt-6 mb-3">Intellectual Property</h2>
        <p>
          The app, including its design, features, and original content, is owned by Bible for Life Stages. 
          Bible verses are sourced from public domain translations or used with permission.
        </p>

        <h2 className="text-lg font-bold mt-6 mb-3">Limitation of Liability</h2>
        <p>
          The app is provided "as is" without warranties of any kind. We are not liable for any 
          damages arising from your use of the app, including but not limited to:
        </p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Decisions made based on AI-generated content</li>
          <li>Interruptions in service</li>
          <li>Loss of data</li>
          <li>Inaccuracies in generated content</li>
        </ul>

        <h2 className="text-lg font-bold mt-6 mb-3">Mental Health Notice</h2>
        <p>
          If you are experiencing a mental health crisis, please contact a qualified professional 
          or crisis helpline. This app is not a substitute for professional mental health care.
        </p>
        <p className="mt-2">
          <strong>National Suicide Prevention Lifeline:</strong> 988<br />
          <strong>Crisis Text Line:</strong> Text HOME to 741741
        </p>

        <h2 className="text-lg font-bold mt-6 mb-3">Changes to Terms</h2>
        <p>
          We may update these terms from time to time. Continued use of the app after changes 
          constitutes acceptance of the new terms.
        </p>

        <h2 className="text-lg font-bold mt-6 mb-3">Contact</h2>
        <p>
          Questions about these terms? Contact us at:<br />
          <a href="mailto:support@bibleforlifestages.com" className="text-primary">support@bibleforlifestages.com</a>
        </p>
      </main>
    </div>
  )
}
